sudo: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install:
  - pip install --upgrade pip setuptools
  - pip install --upgrade pytest pytest-cov coveralls
  - pip install -e .
script:
  - python setup.py test -a -v -a --cov=pyecoregen
after_success:
  - coveralls
